github: [dguo, maxbachmann]
ko_fi: dannyguo
liberapay: dannyguo
custom: ["https://www.paypal.com/donate/?hosted_button_id=VGWQBBD5CTWJU", "https://www.paypal.com/paypalme/DannyGuo", "https://www.buymeacoffee.com/dannyguo"]
