language: rust

os:
    - linux
    - windows

rust:
    - 1.31.0
    - nightly
    - beta
    - stable

matrix:
    allow_failures:
        - rust: nightly

script:
    - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
          cargo test --features readme;
      else
          cargo test;
      fi
